# Generated by Django 3.0.4 on 2020-04-18 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0002_job_result'),
    ]

    operations = [
        migrations.RenameField(
            model_name='result',
            old_name='job_id',
            new_name='job',
        ),
    ]
