# Generated by Django 3.0.4 on 2020-04-18 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0003_auto_20200418_1635'),
        ('uploader', '0003_auto_20200418_0226'),
    ]

    operations = [
    ]
